# Generated by Django 5.1.1 on 2025-01-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('county', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=2)),
                ('zip', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=1)),
            ],
        ),
    ]
