# Generated by Django 5.1.1 on 2025-01-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zip', '0002_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='address',
            name='status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip',
            field=models.CharField(max_length=1000),
        ),
    ]
