# Generated by Django 5.1.1 on 2025-01-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zip', '0003_alter_address_state_alter_address_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address_mapped',
            fields=[
                ('address_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('county', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(max_length=20)),
                ('zip', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(max_length=10)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
