# Generated by Django 5.1.1 on 2025-01-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zip', '0004_address_mapped'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('address_id', models.IntegerField()),
                ('payment_id', models.IntegerField(blank=True, null=True)),
                ('g_id', models.IntegerField(blank=True, null=True)),
                ('g_assigned_by', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_total', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('promo_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('credit_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('new_credit', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('safety_insurance', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('sameday_booking', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('surcharge_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('total_final', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('tip', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('tip_surcharge_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('reserved_at', models.CharField(blank=True, max_length=255, null=True)),
                ('reserved_date', models.CharField(blank=True, max_length=255, null=True)),
                ('cdate', models.DateTimeField(blank=True, null=True)),
                ('accepted_date', models.DateTimeField(blank=True, null=True)),
                ('g_confirm_date', models.DateTimeField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('mdate', models.DateTimeField(blank=True, null=True)),
                ('if_complain', models.CharField(blank=True, max_length=3, null=True)),
                ('delayed', models.CharField(blank=True, max_length=100, null=True)),
                ('ontheway_eta', models.CharField(blank=True, max_length=50, null=True)),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('cancel_date', models.DateTimeField(blank=True, null=True)),
                ('order_from', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
