# Generated by Django 5.1.1 on 2025-01-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zip', '0005_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('hear_from', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('cdate', models.DateTimeField(blank=True, null=True)),
                ('mdate', models.DateTimeField(blank=True, null=True)),
                ('zip', models.CharField(blank=True, max_length=100, null=True)),
                ('register_from', models.CharField(blank=True, max_length=10, null=True)),
                ('referral_url', models.URLField(blank=True, max_length=500, null=True)),
                ('influencer', models.CharField(blank=True, max_length=255, null=True)),
                ('apple_profile_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
